### ISSUE TITLE
ASTDR/ASTDRmc glitch

### ISSUE THREAD

**Issue by nobananasforyou** [realfinder/AVS-Stuff#139]
G'day!

Thanks for these wonderful scripts. I just upgraded to v1.78 and encountered a glitch. I've uploaded a sample along with an image comparison. 

Image Comparison:
https://slow.pics/c/ykjOGizV

Sample:
https://www.dropbox.com/s/tjbq3gsqmb76yae/rt.m2v?dl=0

Script:
MPEG2Source("rt.d2v", cpu=0)
TFM(order=1).Tdecimate()
ASTDR() / ASTDRmc()

Kind Regards

**Comment by realfinder** [comment]
upgraded from... 1.77? or?

anyway the last one now is 1.80 in Community branch https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/ASTDR.avsi

also this normal I think and that why there are mc version, if you still want to use non mc then try with ASTDR(3,15,2,FluxStv=30,edgem=true) since ASTDR default values are high (tempsoftrad, tempsoftth and tempsoftsc) and case this
