### ISSUE TITLE
YLevelsC. Description requirement of few functions.

### ISSUE THREAD

**Issue by TbtBI** [realfinder/AVS-Stuff#49]
Hi.
Comparing original YLevelsC ( http://avisynth.nl/images/YLevels_mt.avsi ) and the one from the latest update here, there is a big difference (8-bit):
```
tv range yuv input
YlevelsC(16,4.5,15,0,240)
```
Can you add some info about:
- filtering_wsb and filtering_wsb - can you add the purpose of those functions? Can you add parameters description?
- scaled444tonative - can you add parameters description?
- smaskmerge - can you add the purpose of that function? Can you add parameters description?

Thanks.

**Comment by realfinder** [comment]
try make 162,97466 in old script as 162.97466, since the old scripts seems has many bugs like https://forum.doom9.org/showpost.php?p=1888805&postcount=40

filtering_wsb = filtering with some borders as it written, sometimes I need things like this to avoid some artifacts/none filtered pixels in frame borders

about scaled444tonative, the original description here https://forum.doom9.org/showthread.php?t=173005 not Enough?

smaskmerge manly made since there are old bug (fixed by now) in mt_merge https://forum.doom9.org/showthread.php?p=1802781#post1802781

**Comment by TbtBI** [comment]
Changing 162,97466 to 162.97466 no visual change.
YlevelsS(16,3.5,15,0,240) (latest update and original) - http://imgbox.com/g/AtXvS35qhn
YlevelsC(16,3.5,15,0,240) (latest update and original) - http://imgbox.com/g/QSRQBFogp1

scaled444tonative has additional parameters (sDev, iDev, onepass...) that are not part of the original script.

**Comment by realfinder** [comment]
it's bug in old expr, if you remove "0 1 clip " they will be same but you will get wrong output with float clip

**Comment by TbtBI** [comment]
Ok.
I did few other tests:
ylevels(19,2.5,200,0,255) # 8-bit vs 32-bit (two different outputs)
ylevelsg(19,2.5,200,0,255) # 8-bit vs 16-bit vs 32-bit (three different outputs)
ylevelss(19,2.5,200,0,255) # 8-bit vs 16-bit vs 32-bit (three different outputs)

**Comment by realfinder** [comment]
indeed, what is the point if you get 100% same output using slower HBD? Unless the difference is very big then maybe there are some issue

**Comment by TbtBI** [comment]
You even didn't check it.
Here 8-bit vs 32-bit - http://imgbox.com/g/54jaRR9nP1

**Comment by realfinder** [comment]
I did check, didn't get that different with

ColorBars
converttoyv12
Convertbits(32)
ylevels(19,2.5,200,0,255)

**Comment by TbtBI** [comment]
Right. I reinstalled my environment and now it looks as expected.
